package aghazadeh.ahmad.smsblocke.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import aghazadeh.ahmad.smsblocke.db.Roles;

import aghazadeh.ahmad.smsblocke.db.RolesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rolesDaoConfig;

    private final RolesDao rolesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rolesDaoConfig = daoConfigMap.get(RolesDao.class).clone();
        rolesDaoConfig.initIdentityScope(type);

        rolesDao = new RolesDao(rolesDaoConfig, this);

        registerDao(Roles.class, rolesDao);
    }
    
    public void clear() {
        rolesDaoConfig.getIdentityScope().clear();
    }

    public RolesDao getRolesDao() {
        return rolesDao;
    }

}
